### ISSUE TITLE
Crash on open inventory 

### ISSUE THREAD

**Issue by codydbgt** [Tschipp/CarryOn#119]
CarryOn+MC1.12.2+v1.9.1

java.lang.NullPointerException: Unexpected error
	at tschipp.carryon.client.event.RenderEvents.renderHand(RenderEvents.java:287)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_492_RenderEvents_renderHand_RenderHandEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:173)
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:673)
	at net.optifine.reflect.ReflectorForge.renderFirstPersonHand(ReflectorForge.java:81)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1047)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:1001)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1968)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Tschipp** [comment]
I thought I fixed this... will be able to look at it in a week

**Comment by cheesealmighty** [comment]
https://paste.ubuntu.com/p/hyrX8m6gb9/

Yup. This is happening on my end too. Although not related to inventory. 
Funny thing is, it was working until today, and yet, I can't join the server now.

**Comment by coolsimulations** [comment]
Also having this same issue with someone on my server. They cannot open their inventory. It seems to only be affecting the one player though.
[crash-2018-07-09_14.07.31-client.txt](https://github.com/Tschipp/CarryOn/files/2178497/crash-2018-07-09_14.07.31-client.txt)

**Comment by maksim789456** [comment]
Same problem -_-
[crash-2018-07-15_21.46.22-client.txt](https://github.com/Tschipp/CarryOn/files/2196002/crash-2018-07-15_21.46.22-client.txt)

**Comment by Tschipp** [comment]
> The person on my server who was crashing had the default Alex model skin. After looking at the source code here, I suggested that they get a Steve model skin. Upon changing their skin, Carry-On no longer crashed on my server.
Hope this helps.

Interesting, thanks

**Comment by Tschipp** [comment]
Still not able to recreate this... I'm running a forge server and joining with a player using the Alex model. Yet I can still pickup blocks, open the inventory and everything and nothing happens...

**Comment by Tschipp** [comment]
Since I'm not able to recreate the issue, I added an extra null-check, hoping this fixes the issue. Does anyone that is experiencing this issue want to help me test this? I'd rather not release a patch if it doesn't actually fix the bug in question. If you want to help with the testing, please reach out on discord: Tschipp
#3159

**Comment by demfels** [comment]
So I had a character on my server with the same issue.  I deleted the NBT player.dat data for Carryon on his file and this fixed it.  He also had Alex as a skin by the way.

Here is the corrupted.dat file: https://drive.google.com/file/d/1k8REV3rs4E9Yah7wA5sIiG-eyThkkzPU/view?usp=sharing

**Comment by Tschipp** [comment]
Ok I'm expected to have a permanent fix tomorrow... rewrote the entire way that arms are rendered. The code that was crashing everyone now doesn't exist anymore
