### ISSUE TITLE
Chest placement issues

### ISSUE THREAD

**Issue by ghost** [Tschipp/CarryOn#186]
### Expected Behavior
Chest should be placed back down with all items included.

### Actual Behavior
Error produced, will not let you place down chest. Forces you to clear.

### Steps to Reproduce
Pickup any chest and attempt to place back down.

### Version of Minecraft, Carry On, Forge
Minecraft Version: 1.12.2
Carry On: MC1.12.2 v1.12.2
Forge: forge-14.23.5.2838

### Screenshots encouraged
![2019-08-31_18 34 28](https://user-images.githubusercontent.com/54756295/64070477-036bea80-cc1e-11e9-9295-ee3661fabb17.png)

**Comment by Tschipp** [comment]
I've been getting tons of report of placing chests lately... can you please include your log? It's the latest.log file

**Comment by Robzekrom** [comment]
Whenever a chest is placed:

[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]: java.lang.NullPointerException
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at eviqnn.silkyspawners.SilkySpawners.blockPlace(SilkySpawners.java:132)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_407_SilkySpawners_blockPlace_EntityPlaceEvent.invoke(.dynamic)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraftforge.event.ForgeEventFactory.onBlockPlace(ForgeEventFactory.java:169)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.world.World.func_190527_a(World.java:3176)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at tschipp.carryon.common.item.ItemTile.func_180614_a(ItemTile.java:117)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:481)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at java.util.concurrent.FutureTask.run(Unknown Source)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[19:05:17] [Server thread/INFO] [STDERR]: [tschipp.carryon.common.item.ItemTile:func_180614_a:198]:     at java.lang.Thread.run(Unknown Source)

**Comment by Tschipp** [comment]
Thanks, I will take a look at it

**Comment by WenXin20** [comment]
I got the same error, even though the chest actually did place.

**Comment by Tschipp** [comment]
Looks like a compat issue with SilkySpawners, not on my side.
