### ISSUE TITLE
Game hang while carrying sheep

### ISSUE THREAD

**Issue by MatthiasMann** [Tschipp/CarryOn#213]
### Expected Behavior
No hang

### Actual Behavior
The game got stuck for 3+ minutes (until I killed the process) but I retrieved several jstack traces before that - all showing the same call stack (only difference between stack traces had been the minimap thread) - this is the Minecraft server thread:
"Server thread" #67 prio=5 os_prio=0 tid=0x00007f1316e98800 nid=0x5cf0 runnable [0x00007f139fcfc000]
   java.lang.Thread.State: RUNNABLE
	at java.util.WeakHashMap.put(WeakHashMap.java:453)
	at java.util.Collections$SetFromMap.add(Collections.java:5468)
	at net.minecraft.item.crafting.Ingredient.<init>(Ingredient.java:51)
	at net.minecraft.item.crafting.Ingredient.func_209357_a(Ingredient.java:155)
	at net.minecraft.item.crafting.Ingredient.func_199804_a(Ingredient.java:160)
	at net.minecraft.entity.passive.SheepEntity.func_184651_r(SheepEntity.java:108)
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:111)
	at net.minecraft.entity.CreatureEntity.<init>(SourceFile:12)
	at net.minecraft.entity.AgeableEntity.<init>(SourceFile:30)
	at net.minecraft.entity.passive.AnimalEntity.<init>(SourceFile:31)
	at net.minecraft.entity.passive.SheepEntity.<init>(SheepEntity.java:100)
	at net.minecraft.entity.EntityType$$Lambda$1261/1033669692.create(Unknown Source)
	at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:412)
	at tschipp.carryon.common.item.ItemCarryonEntity.getEntity(ItemCarryonEntity.java:199)
	at tschipp.carryon.common.item.ItemCarryonEntity.potionLevel(ItemCarryonEntity.java:272)
	at tschipp.carryon.common.item.ItemCarryonEntity.func_77663_a(ItemCarryonEntity.java:157)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:405)
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:265)
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:492)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	- locked <0x000000063e8757b8> (a java.util.Collections$SynchronizedRandomAccessList)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:748)

PS: Is the sheep trying to craft something?

### Steps to Reproduce
No idea - first time it happened - I carried sheep before without issue.

### Version of Minecraft, Carry On, Forge
Minecraft: 1.14.4
Forge: 1.14.4-28.1.104
Carry On: CarryOn+MC1.14.4+v1.12.4

**Comment by MatthiasMann** [comment]
Btw - this is the client thread stack trace at the same time:
"Client thread" #1 prio=5 os_prio=0 tid=0x00007f14a000e000 nid=0x58e5 runnable [0x00007f14aa5f9000]
   java.lang.Thread.State: RUNNABLE
	at java.util.WeakHashMap.put(WeakHashMap.java:453)
	at java.util.Collections$SetFromMap.add(Collections.java:5468)
	at net.minecraft.item.crafting.Ingredient.<init>(Ingredient.java:51)
	at net.minecraft.item.crafting.Ingredient.func_209357_a(Ingredient.java:155)
	at net.minecraft.item.crafting.Ingredient.func_199804_a(Ingredient.java:160)
	at net.minecraft.entity.passive.SheepEntity.func_184651_r(SheepEntity.java:108)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at tschipp.carryon.common.item.ItemCarryonEntity.getEntity(ItemCarryonEntity.java:211)
	at tschipp.carryon.common.item.ItemCarryonEntity.func_77663_a(ItemCarryonEntity.java:149)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:405)
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:265)
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:492)
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70636_d(ClientPlayerEntity.java:734)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232)
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:173)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:165)
	at net.minecraft.client.world.ClientWorld$$Lambda$7337/1902702164.accept(Unknown Source)
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:133)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1344)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/1291485735.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by Tschipp** [comment]
Won't fix on 1.14. Fixed on 1.15. If this is very important, feel free to PR.
