### ISSUE TITLE
Having Create(mod) entities blacklisted doesnt stop you from picking up entities from the mod

### ISSUE THREAD

**Issue by Anatheras** [Tschipp/CarryOn#231]
### Expected Behavior
That i couldnt pick up tile entities from the mod

### Actual Behavior
they get picked up and depending on the tile entity in question it crashes upon placing them down

### Steps to Reproduce
1. Have Create installed
2. Search for a water wheel and place it down
3. Try to pick up the water wheel and place it down
4. Watch as your game crashes

### Version of Minecraft, Carry On, Forge
Minecraft: 1.14.4
CarryOn: 1.12.4
Forge: 28.2.3
Create: 0.2.2a

### Screenshots encouraged
![2020-04-08_07 00 11](https://user-images.githubusercontent.com/31390992/78771540-b2b43100-7966-11ea-9e5b-6846dd3bffce.png)

### Crash Log
---- Minecraft Crash Report ----
// Don't do that.

Time: 4/8/20 6:32 AM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:classloading}
	at com.simibubi.create.modules.contraptions.components.waterwheel.WaterWheelBlock.updateFlowAt(WaterWheelBlock.java:85) ~[?:mc1.14.4_v0.2.2a] {re:classloading}
	at com.simibubi.create.modules.contraptions.components.waterwheel.WaterWheelBlock.updateAllSides(WaterWheelBlock.java:77) ~[?:mc1.14.4_v0.2.2a] {re:classloading}
	at com.simibubi.create.modules.contraptions.components.waterwheel.WaterWheelTileEntity.lazyTick(WaterWheelTileEntity.java:67) ~[?:mc1.14.4_v0.2.2a] {re:classloading}
	at com.simibubi.create.foundation.behaviour.base.SmartTileEntity.initialize(SmartTileEntity.java:61) ~[?:mc1.14.4_v0.2.2a] {re:classloading}
	at com.simibubi.create.modules.contraptions.base.KineticTileEntity.initialize(KineticTileEntity.java:71) ~[?:mc1.14.4_v0.2.2a] {re:classloading}
	at com.simibubi.create.foundation.behaviour.base.SmartTileEntity.func_73660_a(SmartTileEntity.java:47) ~[?:mc1.14.4_v0.2.2a] {re:classloading}
	at com.simibubi.create.modules.contraptions.base.KineticTileEntity.func_73660_a(KineticTileEntity.java:76) ~[?:mc1.14.4_v0.2.2a] {re:classloading}
	at com.simibubi.create.modules.contraptions.base.GeneratingKineticTileEntity.func_73660_a(GeneratingKineticTileEntity.java:43) ~[?:mc1.14.4_v0.2.2a] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95)
	at com.simibubi.create.modules.contraptions.components.waterwheel.WaterWheelBlock.updateFlowAt(WaterWheelBlock.java:85)
	at com.simibubi.create.modules.contraptions.components.waterwheel.WaterWheelBlock.updateAllSides(WaterWheelBlock.java:77)
	at com.simibubi.create.modules.contraptions.components.waterwheel.WaterWheelTileEntity.lazyTick(WaterWheelTileEntity.java:67)
	at com.simibubi.create.foundation.behaviour.base.SmartTileEntity.initialize(SmartTileEntity.java:61)
	at com.simibubi.create.modules.contraptions.base.KineticTileEntity.initialize(KineticTileEntity.java:71)
	at com.simibubi.create.foundation.behaviour.base.SmartTileEntity.func_73660_a(SmartTileEntity.java:47)
	at com.simibubi.create.modules.contraptions.base.KineticTileEntity.func_73660_a(KineticTileEntity.java:76)
	at com.simibubi.create.modules.contraptions.base.GeneratingKineticTileEntity.func_73660_a(GeneratingKineticTileEntity.java:43)

-- Block entity being ticked --
Details:
	Name: create:water_wheel // com.simibubi.create.modules.contraptions.components.waterwheel.WaterWheelTileEntity
	Block: Block{minecraft:air}
	Block location: World: (240,68,47), Chunk: (at 0,4,15 in 15,2; contains blocks 240,0,32 to 255,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{create:water_wheel}[facing=east]
	Block location: World: (240,68,47), Chunk: (at 0,4,15 in 15,2; contains blocks 240,0,32 to 255,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:621)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Lordofthebricks'/63406, l='New World', x=239.28, y=68.00, z=49.17]]
	Chunk stats: ServerChunkCache: 2183
	Level dimension: DimensionType{minecraft:overworld}
	Level name: New World
	Level seed: 7678972730923505457
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (240,69,32), Chunk: (at 0,4,0 in 15,2; contains blocks 240,0,32 to 255,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8996 game time, 8996 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 31692 (now: false), thunder time: 8162 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1612531296 bytes (1537 MB) / 3875012608 bytes (3695 MB) up to 5628231680 bytes (5367 MB)
	CPUs: 6
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6037m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.3
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0
	Mod List: 
		dotHack-Weapons-1.14.4-1.0.0.jar dotHack Weapons {dothack@1.0.0 DONE}
		craftingstation-2.1.6.jar Crafting Station {craftingstation@2.1.6 DONE}
		Mine and Slash-1.14.4-2.9.4.jar Mine and Slash {mmorpg@2.8.0 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		findme-1.14.4-1.1.0.13.jar Find Me {findme@NONE DONE}
		MS Auto-Compat-1.14.4-1.6.0.jar M&S Auto-Compat 1.14.4 {azurecompat@1.6.0 DONE}
		create-mc1.14.4_v0.2.2a.jar Create {create@mc1.14-0.2.2a DONE}
		Waystones_1.14.4-5.1.1.jar Waystones {waystones@5.1.1 DONE}
		Clumps-4.0.1.jar Clumps {clumps@4.0.1 DONE}
		journeymap-1.14.4-5.7.0b1.jar Journeymap {journeymap@1.14.4-5.7.0b1 DONE}
		Controlling-5.0.6.jar Controlling {controlling@5.0.6 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		SereneSeasons-1.14.4-2.0.0.40-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.40 DONE}
		betteranimalsplus-1.14.4-9.0.0.jar Better Animals Plus {betteranimalsplus@9.0.0 DONE}
		branders-enhanced-mob-spawners-v1.14.4-1.5.4.jar Enhanced Mob Spawners {spawnermod@1.5.4 DONE}
		RealisticTorches-1.14.4-3.0.0.jar Realistic Torches {realistictorches@1.14.4-3.0.0 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		walljump-1.14.4-1.3.1.jar Wall-Jump! {walljump@1.14.4-1.3.1 DONE}
		SnowRealMagic-1.14.4-1.5.2.jar Snow! Real Magic! {snowrealmagic@1.5.2 DONE}
		Kiwi-1.14.4-2.6.3.jar Kiwi {kiwi@2.6.3 DONE}
		CarryOn MC1.14.4 v1.12.4.jar Carry On {carryon@1.12.4 DONE}
		JustEnoughResources-1.14.4-0.10.1.76.jar Just Enough Resources {jeresources@0.10.1.76 DONE}
		CraftTweaker-1.14.4-5.0.1.165.jar CraftTweaker {crafttweaker@5.0.1.165 DONE}
		BetterThanMending-1.3.2.jar BetterThanMending {betterthanmending@1.3.2 DONE}
		forge-1.14.4-28.2.3-universal.jar Forge {forge@28.2.3 DONE}
		forge-1.14.4-28.2.3-client.jar Minecraft {minecraft@1.14.4 DONE}
		dwmh-1.14.4-3.1.1.jar Dude! Where's my Horse? {dwmh@1.14.4-3.1.1 DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		AmbientSounds_v3.0.16_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		MouseTweaks-2.13-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.14.4-1.12.5.jar Tool Belt {toolbelt@1.12.5 DONE}
		NaturalProgression-1.14.4-1.3.0b.jar Natural Progression {natural-progression@1.3.0b DONE}
		pamhc2crops-1.14.4-1.0.4.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		invtotem_1.14-1.0.jar Inventory Totem {invtotem@1.0 DONE}
		fairylights-2.1.15-1.14.4.jar Fairy Lights {fairylights@2.1.15 DONE}
		astikorcarts-1.0.2-1.14.4.jar AstikorCarts {astikorcarts@1.0.2 DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		cyclepaintings_1.14-1.1.jar Cycle Paintings {cyclepaintings@1.1 DONE}
		placeableitems-4.0.0.jar Placeable Items {placeableitems@4.0 DONE}
		betteranimals-1.14.4-5.3.0.jar Cyber's Better Animal Models {betteranimals@5.3.0 DONE}
		tombstone-4.3.2-1.14.4.jar Corail Tombstone {tombstone@4.3.2 DONE}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
		structurize-0.10.245-ALPHA.jar Structurize {structurize@0.10.245-ALPHA DONE}
		Mine and Slash - Expansion-1.4.2.30.jar Mine & Slash Expansion {mineandslashexpansion@1.4.2.30 DONE}
		minecolonies-0.10.715-RELEASE-universal.jar Minecolonies {minecolonies@0.10.715-RELEASE DONE}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 DONE}
		easyelytrato_1.14-1.2.jar Easy Elytra Takeoff {easyelytrato@1.2 DONE}
		Aquaculture-1.14.4-2.0.7.jar Aquaculture 2 {aquaculture@1.14.4-2.0.7 DONE}
		BetterBurning-1.14.4-1.0.1.jar BetterBurning {betterburning@1.0.1 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		SoundFilters-0.13_for_1.14.4.jar Sound Filters {soundfilters@0.13_for_1.14.4 DONE}
		horsestats-1.14.4-1.0.1.jar Horse Stats {horsestats@1.0.1 DONE}
		BetterAdvancements-1.14.4-0.1.0.90.jar Better Advancements {betteradvancements@0.1.0.90 DONE}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Player Count: 1 / 8; [ServerPlayerEntity['Lordofthebricks'/63406, l='New World', x=239.28, y=68.00, z=49.17]]
	Data Packs: vanilla, mod:aiimprovements, mod:ambientsounds, mod:appleskin, mod:aquaculture, mod:arl, mod:astikorcarts, mod:azurecompat, mod:betteradvancements (incompatible), mod:betteranimals, mod:betteranimalsplus, mod:betterburning, mod:betterthanmending, mod:carryon, mod:clumps, mod:controlling, mod:craftingstation, mod:crafttweaker, mod:create, mod:curios, mod:cyclepaintings, mod:dothack, mod:dwmh, mod:easyelytrato, mod:fairylights, mod:fastfurnace, mod:fastleafdecay, mod:findme (incompatible), mod:forge, mod:horsestats, mod:invtotem, mod:jei, mod:jeresources (incompatible), mod:journeymap, mod:kiwi, mod:mineandslashexpansion, mod:minecolonies (incompatible), mod:mmorpg, mod:mousetweaks, mod:natural-progression, mod:pamhc2crops, mod:placeableitems, mod:placebo, mod:quark, mod:realistictorches, mod:sereneseasons, mod:snowrealmagic, mod:soundfilters, mod:spawnermod, mod:structurize, mod:swingthroughgrass, mod:tombstone, mod:toolbelt, mod:waila, mod:walljump, mod:waystones
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Tschipp** [comment]
post your config file pls

**Comment by Anatheras** [comment]
Oops, sorry, i forgot to close it, i screwed up in the config and it was listed where it shouldnt so it was an issue on my part. I mean the crash is real, but the blacklisting works to prevent it.
