### ISSUE TITLE
cant catch pixelmon

### ISSUE THREAD

**Issue by D3s0l4ti0n** [Tschipp/CarryOn#236]
### Expected Behavior
capture successful

### Actual Behavior
[00:22:53] [Server thread/ERROR] [FML]: Exception caught during firing event com.pixelmonmod.pixelmon.api.events.CaptureEvent$SuccessfulCapture@7d2c935b:
java.lang.NullPointerException: null
        at io.github.teitss.pixelmoney.listeners.CaptureListener.lambda$onSuccessfulCapture$0(CaptureListener.java:45) ~[CaptureListener.class:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_241]
        at io.github.teitss.pixelmoney.listeners.CaptureListener.onSuccessfulCapture(CaptureListener.java:25) ~[CaptureListener.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_784_CaptureListener_onSuccessfulCapture_SuccessfulCapture.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703) [EventBus.class:?]
        at com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.catchPokemon(EntityEmptyPokeball.java:413) [EntityEmptyPokeball.class:?]
        at com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.onUpdate(EntityEmptyPokeball.java:325) [EntityEmptyPokeball.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:167) [aaa_spongeforge-1.12.2-2838-7.2.0.jar:1.12.2-2838-7.2.0]
        at net.minecraft.world.WorldServer.redirect$zlj000$onCallEntityUpdate(WorldServer.java:4738) [oo.class:?]
        at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) [amu.class:?]
        at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) [oo.class:?]
        at net.minecraft.world.World.updateEntity(World.java:1958) [amu.class:?]
        at net.minecraft.world.World.updateEntities(World.java:1762) [amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:3928) [oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[00:22:53] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[00:22:53] [Server thread/ERROR] [FML]: 0: NORMAL
[00:22:53] [Server thread/ERROR] [FML]: 1: ASM: com.xpgaming.PixelHunt.Listeners.CaptureListener@7814254 onPokemonCapture(Lcom/pixelmonmod/pixelmon/api/events/CaptureEvent$SuccessfulCapture;)V
[00:22:53] [Server thread/ERROR] [FML]: 2: ASM: io.github.teitss.pixelmoney.listeners.CaptureListener@60cbaa99 onSuccessfulCapture(Lcom/pixelmonmod/pixelmon/api/events/CaptureEvent$SuccessfulCapture;)V
[00:22:53] [Server thread/ERROR] [FML]: 3: ASM: noppes.npcs.ScriptPlayerEventHandler$ForgeEventHandler@34f296e9 forgeEntity(Lnet/minecraftforge/fml/common/eventhandler/Event;)V
[00:22:53] [Server thread/ERROR] [FML]: 4: ASM: fr.pokepixel.legendaryplus.events.HandlerPixelmon@561acec2 onCapture(Lcom/pixelmonmod/pixelmon/api/events/CaptureEvent$SuccessfulCapture;)V
[00:22:53] [Server thread/ERROR] [FML]: 5: ASM: fr.flashback083.pixelevent.HandlerEvent@2ba26633 onCapture(Lcom/pixelmonmod/pixelmon/api/events/CaptureEvent$SuccessfulCapture;)V
[00:22:53] [Server thread/ERROR] [FML]: 6: ASM: com.valjean42.rustles.Rustles@1372b33f onCapture(Lcom/pixelmonmod/pixelmon/api/events/CaptureEvent$SuccessfulCapture;)V
[00:22:53] [Server thread/ERROR] [FML]: 7: LOWEST
[00:22:53] [Server thread/ERROR] [FML]: 8: ASM: rs.expand.pixelmonbroadcasts.listeners.CatchListener@365d234f onCatchPokemonEvent(Lcom/pixelmonmod/pixelmon/api/events/CaptureEvent$SuccessfulCapture;)V
[00:22:53] [Server thread/ERROR] [Sponge]: /*********************************************************************************************************************************************/
[00:22:53] [Server thread/ERROR] [Sponge]: /*                                                  Exception occurred during a PhaseState                                                   */
[00:22:53] [Server thread/ERROR] [Sponge]: /*********************************************************************************************************************************************/
[00:22:53] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system makes a best                                                                                                     */
[00:22:53] [Server thread/ERROR] [Sponge]: /* effort to not throw exceptions randomly                                                                                                   */
[00:22:53] [Server thread/ERROR] [Sponge]: /* but sometimes it is inevitable. In most                                                                                                   */
[00:22:53] [Server thread/ERROR] [Sponge]: /* cases, something else triggered this                                                                                                      */
[00:22:53] [Server thread/ERROR] [Sponge]: /* exception and Sponge prevented a crash                                                                                                    */
[00:22:53] [Server thread/ERROR] [Sponge]: /* by catching it. The following stacktrace                                                                                                  */
[00:22:53] [Server thread/ERROR] [Sponge]: /* can be used to help pinpoint the cause.                                                                                                   */
[00:22:53] [Server thread/ERROR] [Sponge]: /*********************************************************************************************************************************************/
[00:22:53] [Server thread/ERROR] [Sponge]: /* The PhaseState having an exception: Tick{Entity}                                                                                          */
[00:22:53] [Server thread/ERROR] [Sponge]: /* The PhaseContext:                                                                                                                         */
[00:22:53] [Server thread/ERROR] [Sponge]: /* org.spongepowered.asm.util.PrettyPrinter@45de4e7f                                                                                         */
[00:22:53] [Server thread/ERROR] [Sponge]: /*                                                                                                                                           */
[00:22:53] [Server thread/ERROR] [Sponge]: /*  StackTrace :                                                                                                                             */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     java.lang.NullPointerException: null                                                                                                  */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     io.github.teitss.pixelmoney.listeners.CaptureListener.lambda$onSuccessfulCapture$0(CaptureListener.java:45)                           */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     java.util.Optional.ifPresent(Unknown Source)                                                                                          */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     io.github.teitss.pixelmoney.listeners.CaptureListener.onSuccessfulCapture(CaptureListener.java:25)                                    */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.ASMEventHandler_784_CaptureListener_onSuccessfulCapture_SuccessfulCapture.invoke(.dynamic) */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)                                            */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753)                                               */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703)                                                           */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.catchPokemon(EntityEmptyPokeball.java:413)                            */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.onUpdate(EntityEmptyPokeball.java:325)                                */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:167)                                                */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.redirect$zlj000$onCallEntityUpdate(WorldServer.java:4738)                                             */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)                                                              */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)                                                   */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.updateEntity(World.java:1958)                                                                               */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.updateEntities(World.java:1762)                                                                             */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.updateEntities(WorldServer.java:3928)                                                                 */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)                                             */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)                                   */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)                                                                   */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                                    */
[00:22:53] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Unknown Source)                                                                                                  */
[00:22:53] [Server thread/ERROR] [Sponge]: /*                                                                                                                                           */
[00:22:53] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2                                                                                                                        */
[00:22:53] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.2-fe189dcf ``
pokeball just stays black hovering 
### Steps to Reproduce

try to catch a pokemon 
### Version of Minecraft, Carry On, Forge

1.12.2

**Comment by D3s0l4ti0n** [comment]
issue resolved our economy plugin got removed when updating mods

**Comment by DBSeamz** [comment]
I had an issue with Pixelmon and CarryOn together: When I pick up a Pixelmon, it works fine. However, immediately upon setting it down, the Pixelmon disappears. I tried sending out one of my own Pixelmon, picking it up, and putting it down...the entity disappeared and my overlay display told me it had fainted.
I am using Forge for 1.12 through the Twitch launcher.
