### ISSUE TITLE
Didn't start with any mods. [Forge 1.19.3]

### ISSUE THREAD

**Issue by AoXGame** [Tschipp/CarryOn#504]
2023-05-17 14:35:46,591 main WARN Advanced terminal features are not available in this environment
[14:35:46] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 44.0.0, --fml.mcVersion, 1.19.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20221207.122022]
[14:35:46] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 20.0.1 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[14:35:47] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/E:/MCServer/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2364!/ Service=ModLauncher Env=SERVER
[14:35:47] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\MCServer\libraries\net\minecraftforge\fmlcore\1.19.3-44.0.0\fmlcore-1.19.3-44.0.0.jar is missing mods.toml file
[14:35:47] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\MCServer\libraries\net\minecraftforge\javafmllanguage\1.19.3-44.0.0\javafmllanguage-1.19.3-44.0.0.jar is missing mods.toml file
[14:35:47] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\MCServer\libraries\net\minecraftforge\lowcodelanguage\1.19.3-44.0.0\lowcodelanguage-1.19.3-44.0.0.jar is missing mods.toml file
[14:35:47] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\MCServer\libraries\net\minecraftforge\mclanguage\1.19.3-44.0.0\mclanguage-1.19.3-44.0.0.jar is missing mods.toml file
[14:35:47] [main/ERROR] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Failed to load mod file META-INF\jarjar\MixinExtras-0.2.0-beta.1.jar from carryon-forge-1.19.3-2.0.5.17.jar
Exception in thread "main" net.minecraftforge.forgespi.locating.ModFileLoadingException: Failed to load mod file carryon-forge-1.19.3-2.0.5.17.jar
        at MC-BOOTSTRAP/fmlloader@1.19.3-44.0.0/net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator.loadModFileFrom(JarInJarDependencyLocator.java:89)
        at MC-BOOTSTRAP/JarJarSelector@0.3.18/net.minecraftforge.jarjar.selection.JarSelector.recursivelyDetectContainedJars(JarSelector.java:144)
        at MC-BOOTSTRAP/JarJarSelector@0.3.18/net.minecraftforge.jarjar.selection.JarSelector.detect(JarSelector.java:122)
        at MC-BOOTSTRAP/JarJarSelector@0.3.18/net.minecraftforge.jarjar.selection.JarSelector.detectAndSelect(JarSelector.java:33)
        at MC-BOOTSTRAP/fmlloader@1.19.3-44.0.0/net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator.scanMods(JarInJarDependencyLocator.java:49)
        at MC-BOOTSTRAP/fmlloader@1.19.3-44.0.0/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:127)
        at MC-BOOTSTRAP/fmlloader@1.19.3-44.0.0/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:166)
        at MC-BOOTSTRAP/fmlloader@1.19.3-44.0.0/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.IllegalArgumentException: Out of range 1 to 1 for length 1
        at JarJarFileSystems@0.3.18/net.minecraftforge.jarjar.nio.pathfs.PathPath.subpath(PathPath.java:97)
        at JarJarFileSystems@0.3.18/net.minecraftforge.jarjar.nio.pathfs.PathPath.relativize(PathPath.java:186)
        at JarJarFileSystems@0.3.18/net.minecraftforge.jarjar.nio.pathfs.PathFileSystem.getOuterTarget(PathFileSystem.java:152)
        at JarJarFileSystems@0.3.18/net.minecraftforge.jarjar.nio.pathfs.PathFileSystem.checkAccess(PathFileSystem.java:225)
        at JarJarFileSystems@0.3.18/net.minecraftforge.jarjar.nio.pathfs.PathFileSystemProvider.checkAccess(PathFileSystemProvider.java:180)
        at java.base/java.nio.file.spi.FileSystemProvider.exists(FileSystemProvider.java:1204)
        at java.base/java.nio.file.Files.exists(Files.java:2509)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.lambda$new$3(Jar.java:80)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:80)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
        at MC-BOOTSTRAP/fmlloader@1.19.3-44.0.0/net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:38)
        at MC-BOOTSTRAP/fmlloader@1.19.3-44.0.0/net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator.loadModFileFrom(JarInJarDependencyLocator.java:84)

### Version of Minecraft, Carry On, Forge/Fabric
1.19.3 Forge

**Comment by Tschipp** [comment]
What other mods are you using?
