### ISSUE TITLE
Crashing upon picking up mob in singleplayer. In Multiplayer it doesn't work v1.20.6 Fabric

### ISSUE THREAD

**Issue by Lelslolslal** [Tschipp/CarryOn#651]

**Comment by Tschipp** [comment]
Do you have a log?

**Comment by Ujjwal-Rohilla** [comment]
Probably the same issue here. Running on fabric 1.20.6, Aternos

Log of when i try to join:
```
	[11:05:51] [Server thread/INFO]: ThatUnkn0wnDude[/**.**.**.**:55141] logged in with entity id 15 at (-122.3386966109293, 58.0, -448.1626327634977)
[11:05:51] [Netty Epoll Server IO #3/ERROR]: Error sending packet clientbound/minecraft:custom_payload
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (carryon:sync_scripts)
	at net.minecraft.network.handler.PacketCodecDispatcher.handler$zjk000$fabric-networking-api-v1$encode(PacketCodecDispatcher.java:547) ~[server-intermediary.jar:?]
	at net.minecraft.network.handler.PacketCodecDispatcher.encode(PacketCodecDispatcher.java:55) ~[server-intermediary.jar:?]
	at net.minecraft.network.handler.PacketCodecDispatcher.encode(PacketCodecDispatcher.java:14) ~[server-intermediary.jar:?]
	at net.minecraft.network.handler.EncoderHandler.encode(EncoderHandler.java:26) ~[server-intermediary.jar:?]
	at net.minecraft.network.handler.EncoderHandler.encode(EncoderHandler.java:12) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.network.ClientConnection$2.write(class_2535.java:518) ~[server-intermediary.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.network.ClientConnection.sendInternal(ClientConnection.java:342) ~[server-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.method_52917(ClientConnection.java:337) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassCastException: class tschipp.carryon.networking.clientbound.ClientboundSyncScriptsPacket cannot be cast to class net.minecraft.class_8711 (tschipp.carryon.networking.clientbound.ClientboundSyncScriptsPacket and net.minecraft.class_8711 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @68f1b17f)
	at net.minecraft.network.codec.PacketCodec$6.encode(class_9139.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.network.packet.CustomPayload$1.encode(class_8710.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.network.packet.CustomPayload$1.encode(class_8710.java:57) ~[server-intermediary.jar:?]
	at net.minecraft.network.packet.CustomPayload$1.encode(class_8710.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.network.codec.PacketCodec$8.encode(class_9139.java:81) ~[server-intermediary.jar:?]
	at net.minecraft.network.codec.PacketCodec$9.encode(class_9139.java:97) ~[server-intermediary.jar:?]
	at net.minecraft.network.codec.PacketCodec$9.encode(class_9139.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.network.handler.PacketCodecDispatcher.encode(PacketCodecDispatcher.java:53) ~[server-intermediary.jar:?]
	... 31 more
[11:05:51] [Server thread/INFO]: ThatUnkn0wnDude joined the game
[11:05:52] [Server thread/INFO]: ThatUnkn0wnDude lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (carryon:sync_scripts)
[11:05:52] [Server thread/INFO]: ThatUnkn0wnDude left the game
[11:05:52] [Server thread/INFO]: [voicechat] Disconnecting client ThatUnkn0wnDude
```

Thanks

**Comment by Tschipp** [comment]
Should be fixed with the latest version
