### ISSUE TITLE
Crash upon entering world 1.21 forge

### ISSUE THREAD

**Issue by Aceplante** [Tschipp/CarryOn#683]
Hope this helps
```
Description: Exception in server tick loop

java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class tschipp.carryon.common.carry.CarryOnDataManager$ICarrying (net.minecraft.server.level.ServerPlayer is in module minecraft@1.21.1 of loader 'TRANSFORMER' @1984212d; tschipp.carryon.common.carry.CarryOnDataManager$ICarrying is in module carryon@2.2.2 of loader 'TRANSFORMER' @1984212d)
	at TRANSFORMER/carryon@2.2.2/tschipp.carryon.common.carry.CarryOnDataManager.getCarryData(CarryOnDataManager.java:33) ~[carryon-forge-1.21.1-2.2.2.11.jar!/:2.2.2.11] {re:classloading}
	at TRANSFORMER/carryon@2.2.2/tschipp.carryon.CarryOnCommon.onCarryTick(CarryOnCommon.java:102) ~[carryon-forge-1.21.1-2.2.2.11.jar!/:2.2.2.11] {re:classloading}
	at TRANSFORMER/carryon@2.2.2/tschipp.carryon.events.CommonEvents.onServerTick(CommonEvents.java:182) ~[carryon-forge-1.21.1-2.2.2.11.jar!/:2.2.2.11] {re:classloading}
	at TRANSFORMER/carryon@2.2.2/tschipp.carryon.events.__CommonEvents_onServerTick_Post.invoke(.dynamic) ~[carryon-forge-1.21.1-2.2.2.11.jar!/:2.2.2.11] {re:classloading,pl:eventbus:B}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:48) ~[eventbus-6.2.8.jar!/:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:304) ~[eventbus-6.2.8.jar!/:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:290) ~[eventbus-6.2.8.jar!/:?] {}
	at TRANSFORMER/forge@52.0.10/net.minecraftforge.event.ForgeEventFactory.post(ForgeEventFactory.java:228) ~[forge-1.21.1-52.0.10-universal.jar!/:?] {re:classloading}
	at TRANSFORMER/forge@52.0.10/net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:831) ~[forge-1.21.1-52.0.10-universal.jar!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:937) ~[forge-1.21.1-52.0.10-client.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:109) ~[forge-1.21.1-52.0.10-client.jar!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:701) ~[forge-1.21.1-52.0.10-client.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[forge-1.21.1-52.0.10-client.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {}
```

**Comment by Nzuri07** [comment]
As far as I'm aware it's because carryon isn't actually compatible with 1.21+ Minecraft versions because it requires java 21 and carryon is made for java 17, a fix may be to downgrade your java version to 17 but I didn't bother to test if that worked (too much trouble for this crap), otherwise I believe we'd have to wait for a version that does work

anyway be aware I probably have no idea what I'm talking about but this might be it 😀

**Comment by Samoggino** [comment]
same issue, I have Java 21 and my modpack is on 1.21.1

**Comment by Tschipp** [comment]
I am invesitgating this, but I don't think the java version is the problem here
